**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
n1 = np.zeros(10)
n1[4] = 1
print(n1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a = int(input('Enter 1st Number: '))
b = int(input('Enter 2nd Number: '))
n2 = np.random.random(a*b).reshape((a,b))
print(n2)
print('\nSum of the array:',np.sum(n2),'\nAverage :',np.mean(n2))

Enter 1st Number: 5
Enter 2nd Number: 4
[[0.47479792 0.56620971 0.35139361 0.74515524]
 [0.90389101 0.18455764 0.05378669 0.89721946]
 [0.21764012 0.40469168 0.61633674 0.06125294]
 [0.06750832 0.22486103 0.72207592 0.83429213]
 [0.52537689 0.34661109 0.31565449 0.94187882]]

Sum of the array: 9.455191441327093 
Average : 0.47275957206635466


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
a = int(input('Enter Number of Rows: '))
b = int(input('Enter Number of Columns: '))

n3 = np.ones(a*b).reshape((a,b))
for i in range(n3.shape[0]):
  for j in range(n3.shape[1]):
    if(i==0 or i==n3.shape[0]-1):
      pass
    elif(j == 0 or j == n3.shape[1]-1):
      pass
    else:
      n3[i][j] = 0
print(n3)

Enter Number of Rows: 5
Enter Number of Columns: 6
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
n4 = np.linspace(0,1,12)[1:-1]
print(n4)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# No

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
n6 = np.zeros(25).reshape((5,5))
for i in range(5):
  n6[i] = np.arange(5)
print(n6)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
n7 = np.random.randint(1,100,20).reshape((10,2))
print(n7)
point = np.array([2,3])

Dist = np.zeros(10)
for i in range(10):
  Dist[i] = ((n7[i][0]-point[0])**2 + (n7[i][1]-point[1])**2)**(0.5)
print("Distances of Point From The Matrix :\n",Dist)

Dist2 = np.sqrt(np.sum((n7-point)**2,axis=1))
print('\n',Dist2)

[[57 62]
 [36 15]
 [59 79]
 [ 1 77]
 [45 20]
 [26 71]
 [ 7 61]
 [47 67]
 [ 7 47]
 [ 1 31]]
Distances of Point From The Matrix :
 [80.65977932 36.05551275 95.         74.00675645 46.23851209 72.11102551
 58.21511831 78.23681998 44.28317965 28.01785145]

 [80.65977932 36.05551275 95.         74.00675645 46.23851209 72.11102551
 58.21511831 78.23681998 44.28317965 28.01785145]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
a = np.random.random(336).reshape((6,7,8))
b = 100
# Elements in a single array -> no_of_row*no_of_cols
print(a.shape[0])
c = a.shape[1]*a.shape[2]
array_no = b//c
row_no = (b-c)//a.shape[1]
col = b- c*array_no - a.shape[1]*row_no-1
n8 = tuple((array_no,row_no,col))
print(n8)
#Returns 1,6,1 -> 1*56 + 7*6 +1 == 99 ==> 100th Element

6
(1, 6, 1)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
a = '1 2 3 4 -8 -10'
x = a.split()
n9 = np.arange(len(x),dtype='float')
for i in range(len(x)):
  n9[i] = x[len(x)-i-1]
print(n9)


[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
n10 = np.random.random(6)
n10 = np.array([33.17344305, 45.61961654, 82.05405781 ,80.9647098,  68.82830233 ,91.52064278])

def softmax(arr_):
  den = np.sum(np.exp(arr_))
  return np.exp(arr_)/den
softmax(n10)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
a= np.array([[0, 1, 2, 3, 4],[5, 6 ,7, 8,9]])
b = np.array([[1,2,3,4,5],[5,6,7,8,9]])
l = [a,b]

for i in range(1,len(l)):
    a = np.vstack((a,l[i]))
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 2 3 4 5]
 [5 6 7 8 9]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
date_array = np.array(['2020-09-15',  '2020-09-25'])

np.arange(date_array[0],date_array[1],dtype='datetime64')

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
n14 = np.random.random(20).reshape(4,5)

x= np.mean(n14,axis=1)
# print(n14,(n14-m),sep='\n\n')


x = x.reshape(-1,1)

print(n14,(n14-x),sep='\n\n')

[[0.36841374 0.75738462 0.84420533 0.82748112 0.68704166]
 [0.51808819 0.63240816 0.09940496 0.28131588 0.92664422]
 [0.62691855 0.44372013 0.68890982 0.66041294 0.68117751]
 [0.1553766  0.21768123 0.09300259 0.41287247 0.00172127]]

[[-0.32849156  0.06047933  0.14730004  0.13057583 -0.00986363]
 [ 0.02651591  0.14083588 -0.39216732 -0.2102564   0.43507194]
 [ 0.00669076 -0.17650766  0.06868203  0.04018515  0.06094972]
 [-0.02075423  0.0415504  -0.08312824  0.23674164 -0.17440956]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
n15 = np.random.random(20).reshape(4,5)
# First Approach -> Using Extra Variables
'''
# x,y = n15.transpose()[0],n15.transpose()[1]
# print(n15,x,y,sep='\n\n',end='\n\n')
# n15[:,0] = y
# n15[:,1] = x
# print(n15)

'''
print(n15,end='\n\n')
n15[:,:2] = n15[:,1::-1]
print(n15)

[[0.22219437 0.22618439 0.60659838 0.21314946 0.08718827]
 [0.95962033 0.69499508 0.03955581 0.92348831 0.15866925]
 [0.43528386 0.41945766 0.8429965  0.76761847 0.66702776]
 [0.29460974 0.65203253 0.60160521 0.80880504 0.00919931]]

[[0.22618439 0.22219437 0.60659838 0.21314946 0.08718827]
 [0.69499508 0.95962033 0.03955581 0.92348831 0.15866925]
 [0.41945766 0.43528386 0.8429965  0.76761847 0.66702776]
 [0.65203253 0.29460974 0.60160521 0.80880504 0.00919931]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
n16 = np.random.randint(1,24,16).reshape((4,4))
n16[n16%2 != 0] = -1
print(n16)


[[-1 -1  6 -1]
 [ 6 10 -1 -1]
 [ 2 12 16 -1]
 [22  6 -1 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=d = np.zeros(5).astype('int8')
# Basic Logic
for i in range(len(a)):
  if(a[i]>=b[i]):
    c[i] = a[i]
  else:
    c[i] = b[i]
print(c,end='\n\n')

# Through Numpy Function -> Np.maximum
d = np.maximum(a,b)
print(d)

[6 3 1 7 8]

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3546, 5786, 4642, 5651, 6670],
       [7500, 1897, 8889, 4681, 9483],
       [4846, 1911, 4933,  865,  266],
       [1541, 7415, 7913, 3534, 6247],
       [6152, 3794, 5878, 4781, 5736],
       [8908, 1072, 9118,  862, 6157],
       [8865, 7203,  826, 1965, 7665],
       [4711, 3829, 7197, 1776, 6857]])

In [ ]:
# First Part
arr = np.random.randint(low=1, high=100, size=(8, 5))

alternate_columns = arr[:, ::2]

print(alternate_columns)



[[48 82 87]
 [51 70 92]
 [49 86 52]
 [62 22 86]
 [60 18 98]
 [35 90 56]
 [31 77 98]
 [18 52 15]]


In [ ]:
# Second part
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

x = np.min(arr1,axis=0)
y = np.max(arr1,axis=0)
print(arr1,sep='\n\n\n')
print(x,y,sep='\n\n',end='\n\n')
arr1 = (arr1-x)/(y-x)
print(arr1)

[[4237 8581 1734 3634  299]
 [7514 5728 4085 5308 9954]
 [2871 6591  188 5528 7752]
 [1331 9784 3238 4887 1548]
 [9767 3295 6366 6139 1811]
 [7497 7506 8200 6268 4126]
 [2452 6195 2783 7759 2122]
 [7016 4542 7755 7070 6977]]
[1331 3295  188 3634  299]

[9767 9784 8200 7759 9954]

[[0.34447606 0.81460934 0.19296056 0.         0.        ]
 [0.7329303  0.37494221 0.48639541 0.40581818 1.        ]
 [0.18255097 0.50793651 0.         0.45915152 0.77193164]
 [0.         1.         0.38067898 0.30375758 0.12936302]
 [1.         0.         0.77109336 0.60727273 0.1566028 ]
 [0.73091513 0.64894437 1.         0.63854545 0.39637494]
 [0.13288288 0.44691016 0.32388917 1.         0.18881409]
 [0.67389758 0.19217137 0.94445831 0.8329697  0.69166235]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
def fetch_nth_element(arr,n):
  if(arr.ndim ==1):
    a = np.sort(arr)
    n = n%arr.size
    if(np.ndim(a) == 1):
      print(arr,np.flip(a)[n-1],sep="\n\n",end='\n\n')
  else:
    print("Enter 1-D Array",sep='\n\n')


n19 = np.random.randint(1,20,8)
n19_  = np.random.randint(1,35,14).reshape(2,7)
fetch_nth_element(n19,5)
fetch_nth_element(n19_,5)

[ 4 12 19 11 17 13 18 11]

12

Enter 1-D Array


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here