In [1]:
import numpy as np

***Functions Involving Manipulation of NumPy Arrays***

- np.sort
- np.append
- np.concatenate
- np.unique
- np.where
- np.cumsum
- np.cumprod
- np.delete

- *Set Related Functions*

In [8]:
a = np.array([4,7,-21,345,67,45,-23,10,9,5,239])

In [12]:
print(np.sort(a))

[-23 -21   4   5   7   9  10  45  67 239 345]


In [15]:
print(a)
a = np.append(a,99)
print(a)

[  4   7 -21 345  67  45 -23  10   9   5 239]
[  4   7 -21 345  67  45 -23  10   9   5 239  99]


In [27]:
b = np.random.random(a.shape[0])
b

array([0.97076807, 0.55233828, 0.4053036 , 0.9687231 , 0.17803163,
       0.99114913, 0.23925937, 0.0423529 , 0.05567876, 0.88173811,
       0.86029085, 0.79145943])

In [35]:
c = np.arange(1,7).reshape(2,3)
d = np.arange(7,13).reshape(2,3)
np.concatenate((c,d),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [36]:
e = np.array([2,8,9,0,4,5,6,8,9,2])
print(e)
print(np.unique(e))

[2 8 9 0 4 5 6 8 9 2]
[0 2 4 5 6 8 9]


In [40]:
a

array([  4,   7, -21, 345,  67,  45, -23,  10,   9,   5, 239,  99])

In [43]:
a[np.where(a>30)]

array([345,  67,  45, 239,  99])

In [45]:
a

array([  4,   7, -21, 345,  67,  45, -23,  10,   9,   5, 239,  99])

In [54]:
print(a[np.argmin(a)])
print(a[np.argmax(a)])

-23
345


In [59]:
a[5] = 0

In [60]:
print(np.cumsum(a))
print(np.cumprod(a))

[  4  11 -10 335 402 402 379 389 398 403 642 741]
[        4        28      -588   -202860 -13591620         0         0
         0         0         0         0         0]


In [64]:
print(np.percentile(a,50))

8.0


In [66]:
np.median(a) == np.percentile(a,50)

True

In [70]:
a = np.delete(a,0)

In [71]:
a

array([  7, -21, 345,  67,   0, -23,  10,   9,   5, 239,  99])

In [76]:
np.isin(a,-23).sum()
# Returns a boolean array
# Applying sum to it returns 0 xero if all the lemenbts of the array are false
# ELse the No i spresent

1

In [78]:
np.flip(a,axis=0)

array([ 99, 239,   5,   9,  10, -23,   0,  67, 345, -21,   7])

In [79]:
sample = np.arange(1,7).reshape(2,3)

In [84]:
print(sample,end='\n\n')
print(np.flip(sample,axis=0),end='\n\n')
print(np.flip(sample,axis=1),end='\n\n')
print(np.flip(sample,axis=[0,1]))

[[1 2 3]
 [4 5 6]]

[[4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]]

[[6 5 4]
 [3 2 1]]


In [87]:
np.put(a,0,5)

In [88]:
a

array([  5, -21, 345,  67,   0, -23,  10,   9,   5, 239,  99])

In [90]:
np.put(a,3,90)

In [91]:
a

array([  5, -21, 345,  90,   0, -23,  10,   9,   5, 239,  99])

In [92]:
np.put(a,3,55)
a

array([  5, -21, 345,  55,   0, -23,  10,   9,   5, 239,  99])

In [93]:
# Set Functions
s1 = np.arange(3,9)
s2 = np.arange(6,12)

In [95]:
print(np.union1d(s1,s2))
print(np.intersect1d(s1,s2))
print(np.setdiff1d(s1,s2))
print(np.setdiff1d(s2,s1))
print(np.setxor1d(s1,s2))

[ 3  4  5  6  7  8  9 10 11]
[6 7 8]
[3 4 5]
[ 9 10 11]
[ 3  4  5  9 10 11]
