# Numpy

- Numpy in a Library in Python which stands for **Numerical Python**


---

*It is used for creating n-dimensional arrays along with various functions related to statistics & Linear Algebra which are very useful in Machine Learning & AI.*

This Notebook is a Guide to NumPy and covers most useful Functions needed in Data SCience & Machine Learning.

### Topics Covered
- Creating NumPy arrays
- Imp Attributes
- Mathematical Operations in NumPy
- Functions


In [89]:
# Importing the Library

import numpy as np

In [90]:
# Creating n-dimensional NumPy Arrays
# n = 1,2,3,4.....

n1 = np.array([1,2,3,4,5]) #1-D Array
print(n1)
print(type(n1))

n2 = np.array([[1,2],[3,4],[5,6]]) # 2-D Array
n3 = np.array(([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))

print(n2,type(n2),n2.ndim)
print(n3,type(n3),n3.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'> 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'> 3


# Various Ways of Creating NumPy Arrays

 1. arange
 2. ones
 3. Zeroes
 4. random
 5.linespace
 6. identity
 7. eye


In [91]:
a = np.arange(0,50,5)
b = np.ones((3,2))
c = np.zeros(4)
d = np.random
e = np.linspace(1,10,10)
f = np.identity(2)
g = np.eye(3,3)


In [92]:
print(a,b,c,d,e,f,g,sep='\n')

[ 0  5 10 15 20 25 30 35 40 45]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0. 0. 0. 0.]
<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




---



*Special *NumPy* Attributes*


###### ndim -> Returns the dimesnsions of the Array
###### shape -> Returns the shape of the array
######  size -> Returns the size of the NumPy Array
###### dtype -> Returns the data type of the Array
###### astype -> Converts the array into a specific datatype

In [93]:
print(n1.ndim)
print(n2.shape)
print(n3.size)
print(a.dtype)
a = a.astype('int8')
print(a.dtype)

1
(3, 2)
12
int64
int8


# NumPy : Operations & Functions

- Scaler Operations On Matrix

1. Addition
2. Multiplication
3. Division
4. Subtraction


- Relational Operations

5. Equality | Inequality Operations -> returns boolean values

- Vector Operations

6. Multiplication of Matrices

# *Array Functions*
- Basic Mathematical & Statistical Functions

1. min
2. max
3. len
4. prod
5. And Additional Functions such as -> log/Exponent
- Some Statistical Functions
5. mean
6. median
7. mode
8. st. Deviation
9. Variance

# Functions Related to Array Manipulation

- Reshape
- Ravel
- Transpose



In [94]:
n1

array([1, 2, 3, 4, 5])

In [95]:
#SCaler Operations

print(n1+5)
print(n1-1)
print(n1*2)
print(n1/3)

[ 6  7  8  9 10]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [96]:
# Relational Operations
# Returns Boolean Arrays , where the condition gets satisfied , it returns true , else false
print(n1 == 5)
print(n1>5)
print(n1>=5)
print(n1<5)
print(n1<=5)
print(n1!=5)

[False False False False  True]
[False False False False False]
[False False False False  True]
[ True  True  True  True False]
[ True  True  True  True  True]
[ True  True  True  True False]


In [97]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([6,7,8,9,10])
print(n1*n2)

[ 6 14 24 36 50]


In [98]:
n2 = np.arange(1,50,10)
print(n1*n2)

[  1  22  63 124 205]


In [99]:
print(n1.sum())
print(n1.min())
print(n1.max())
print(n1.prod())

print(n1.mean())
print(np.median(n1)) # Median is a functions of numpy , while mean , sum , prod are methods
print(n1.std())
print(n1.var())

15
1
5
120
3.0
3.0
1.4142135623730951
2.0


In [100]:
print(np.log2(n1))
print(np.exp(n1))
print(np.ceil(n1+(0.99)))
print(np.floor(n1+0.87))

[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


In [101]:
# Reshape

x = np.arange(25).reshape(5,5)
print(x,end='\n\n')
y = np.random.random(16).reshape(2,4,2)
print(y,end='\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[[0.07140663 0.4121099 ]
  [0.06644183 0.16090804]
  [0.21102486 0.31085417]
  [0.04448258 0.48879952]]

 [[0.42887335 0.90346613]
  [0.51667438 0.08069685]
  [0.96280833 0.52973168]
  [0.65964623 0.95573265]]]


In [102]:
print(x.transpose())

[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [103]:
print(x.reshape(5,5),end='\n\n')
print(x.reshape(-1),end='\n\n')
print(x.ravel())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [104]:
print(y.reshape(8,2).transpose())

[[0.07140663 0.06644183 0.21102486 0.04448258 0.42887335 0.51667438
  0.96280833 0.65964623]
 [0.4121099  0.16090804 0.31085417 0.48879952 0.90346613 0.08069685
  0.52973168 0.95573265]]


In [105]:
# Dot Product
m = np.arange(1,6).reshape(1,5)
n = np.arange(6,11).reshape(5,1)

# Dot product of (a) of size mXn and (b) size pXq is only possible when n==p
print(m*n) # Vector Product
print('\n')
print(m.dot(n)) #dot function
print('\n')
print(n.dot(m)) # SImilar to n*m

[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]


[[130]]


[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]
