In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
arr = np.array([[92,90,74],[6,63,93],[15,93,96],[70,60,48]])

In [3]:
# i) First Part
print(np.sort(arr,axis=1),end='\n\n')

# ii) Second Part
ind = np.argsort(arr[:,1])
print(arr[ind],end='\n\n')

# iii) Third Part
a = np.amax(arr,axis=1)
indices = np.argsort(a)
print(arr[indices],end='\n\n')

# iv) Fourth Part
t = np.sort(np.ravel(arr))
print(t.reshape(arr.shape))

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

[[70 60 48]
 [92 90 74]
 [ 6 63 93]
 [15 93 96]]

[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [4]:
# code here

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [5]:
arr = np.array([[1,2,3,3,1,1],[0,9,1,2,8,8],[1,2,3,8,8,8],[1,2,3,3,1,1]])
# part - i
a1 = np.unique(arr,axis=0)
print(a1,end='\n\n')

# part - ii
a2 = np.unique(arr,axis=1)
print(a2)

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [6]:
arr = [[1,2,3,4,5],[10,-3,30,6,7],[3,2,5,8,9],[9,7,3,2,1]]
print(arr,end='\n\n')
np.flip(arr,axis=[0,1])

[[1, 2, 3, 4, 5], [10, -3, 30, 6, 7], [3, 2, 5, 8, 9], [9, 7, 3, 2, 1]]



array([[ 1,  2,  3,  7,  9],
       [ 9,  8,  5,  2,  3],
       [ 7,  6, 30, -3, 10],
       [ 5,  4,  3,  2,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [7]:
arr = np.array([[1,2,3,4,5],[10,-3,30,4,5],[3,2,5,-4,5],[9,7,3,6,5]])
arr.shape[0]

4

In [8]:
a = [arr]
print(a,type(a))

[array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])] <class 'list'>


In [9]:
np.where(np.any([arr>6],axis=1))

(array([0, 0, 0]), array([0, 1, 2]))

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [10]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [11]:
ans = np.append(arr1,np.append(arr2,arr3))

In [12]:
print(ans,type(ans))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [13]:
import numpy as np

np.random.seed(400)
arr_t = np.random.randint(100, 1000, 200).reshape((1, 200))

In [14]:
min_t = np.min(arr_t.ravel())
print(min_t)
max_t = np.max(arr_t.ravel())
print(max_t)

103
998


In [17]:
arr_t[arr_t!=min_t]

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [19]:
arr_t = arr_t[arr_t!=max_t]

In [20]:
print(arr_t,end='\n\n')
print(arr_t.size)

[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
 173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
 771 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922
 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325
 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395
 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618
 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291
 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883
 588]

199


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [21]:
arr8 = np.linspace(100,700,endpoint=False)
arr8

array([100., 112., 124., 136., 148., 160., 172., 184., 196., 208., 220.,
       232., 244., 256., 268., 280., 292., 304., 316., 328., 340., 352.,
       364., 376., 388., 400., 412., 424., 436., 448., 460., 472., 484.,
       496., 508., 520., 532., 544., 556., 568., 580., 592., 604., 616.,
       628., 640., 652., 664., 676., 688.])

In [22]:
np.clip(arr8,a_min=100,a_max=200)

array([100., 112., 124., 136., 148., 160., 172., 184., 196., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200.])

In [23]:
np.random.seed(42)
random_array = np.random.randint(100, 701,size=(1,25))

In [24]:
random_array = np.sort(random_array)

In [25]:
nrandom_array = np.clip(random_array,a_min=100,a_max=200)

In [ ]:
nrandom_array

In [27]:
np.cumsum(nrandom_array)

array([ 120,  291,  478,  677,  877, 1077, 1277, 1477, 1677, 1877, 2077,
       2277, 2477, 2677, 2877, 3077, 3277, 3477, 3677, 3877, 4077, 4277,
       4477, 4677, 4877])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [33]:
n9 = np.random.random(size=(1,25))
n9 = n9.ravel()
n9

array([0.18657006, 0.892559  , 0.53934224, 0.80744016, 0.8960913 ,
       0.31800347, 0.11005192, 0.22793516, 0.42710779, 0.81801477,
       0.86073058, 0.00695213, 0.5107473 , 0.417411  , 0.22210781,
       0.11986537, 0.33761517, 0.9429097 , 0.32320293, 0.51879062,
       0.70301896, 0.3636296 , 0.97178208, 0.96244729, 0.2517823 ])

In [35]:
n9 = np.round(n9,decimals=3)

In [37]:
print(np.percentile(n9,0) == np.min(n9))
print(np.percentile(n9,100) == np.max(n9))
print(np.percentile(n9,51)-np.percentile(n9,50))

True
True
0.02016000000000001
